### PR TITLE
Remote write authorization config

### LINKED ISSUE #10: Prometheus remote write config
Prometheus remote write config can add two types of Authorization headers: basic auth e bearer token.
As described on the documentation:
```
# The URL of the endpoint to send samples to.
url: <string>

# Timeout for requests to the remote write endpoint.
[ remote_timeout: <duration> | default = 30s ]

# List of remote write relabel configurations.
write_relabel_configs:
  [ - <relabel_config> ... ]

# Sets the `Authorization` header on every remote write request with the
# configured username and password.
# password and password_file are mutually exclusive.
basic_auth:
  [ username: <string> ]
  [ password: <string> ]
  [ password_file: <string> ]

# Sets the `Authorization` header on every remote write request with
# the configured bearer token. It is mutually exclusive with `bearer_token_file`.
[ bearer_token: <string> ]

# Sets the `Authorization` header on every remote write request with the bearer token
# read from the configured file. It is mutually exclusive with `bearer_token`.
[ bearer_token_file: /path/to/bearer/token/file ]
```

The run.sh script, on bb-promster, just add the the remote_url as the code shows:

```
# the user can also configure a remote url to send prometheus metrics to 
if [[ "$REMOTE_WRITE_URL" != "" ]]; then
    cat >> "/prometheus.yml.tmpl" <<- EOM
remote_write:
  - url: $REMOTE_WRITE_URL
EOM
fi
```
In order to support others prometheus' remote config, I propose adding more two env variables: REMOTE_BEARER_TOKEN and REMOTE_BASIC_AUTH. So the run.sh script can add the config if one of them is set.

### PR DESCRIPTION
**Pull request by gutorc92**
Signed-off-by: Gustavo Coelho <gutorc@hotmail.com>

This pull request closes  #10.

### CODE REVIEW

**Comment by eabili0** [comment]
@gutorc92, issue #10 only mentions `REMOTE_WRITE_BEARER_TOKEN`. Please, update your PR to include only `REMOTE_WRITE_BEARER_TOKEN `

**Comment by eabili0** [comment]
Also, we should add references to the new env at the `README` and `docker-compose.yml` files

**Comment by gutorc92** [comment]
> Also, we should add references to the new env at the `README` and `docker-compose.yml` files.

I added the env on README but docker-compose does not have an example of remote write.

**Comment by eabili0** [comment]
@gutorc92, I'll sunset this PR for now. We'll look again at this PR once we get back on track with security for the multi-tenant architecture... Thanks!

**Pull request closed without merging**
